# Generated by Django 5.0.3 on 2025-01-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_historicalinventaire_departement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmplacementTag',
        ),
        migrations.RemoveField(
            model_name='emplacement',
            name='code_barre',
        ),
        migrations.RemoveField(
            model_name='historicalemplacement',
            name='code_barre',
        ),
        migrations.RemoveField(
            model_name='historicallocation',
            name='code_barre',
        ),
        migrations.RemoveField(
            model_name='historicalzone',
            name='code_barre',
        ),
        migrations.RemoveField(
            model_name='location',
            name='code_barre',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='code_barre',
        ),
    ]
