# Generated by Django 5.0.3 on 2025-01-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_delete_emplacementtag_remove_emplacement_code_barre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code_article',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='code_article',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
