# Generated by Django 5.0.3 on 2025-10-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_alter_article_code_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperation_article',
            name='date_operation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaloperation_article',
            name='prix',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation_article',
            name='date_operation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation_article',
            name='prix',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
