# Generated by Django 5.0.3 on 2026-04-01 20:56

from django.db import migrations


def seed_type_tags(apps, schema_editor):
    TypeTag = apps.get_model('masterdata', 'type_tag')
    for nom in ['RFID', 'Code-Barre', 'QR Code']:
        TypeTag.objects.get_or_create(nom=nom)


def reverse_seed(apps, schema_editor):
    TypeTag = apps.get_model('masterdata', 'type_tag')
    TypeTag.objects.filter(nom__in=['RFID', 'Code-Barre', 'QR Code']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_remove_historicalitem_code_barre_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_type_tags, reverse_seed),
    ]
