# Generated by Django 5.0.3 on 2026-04-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_fix_inventaire_statut_etat_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveitem',
            name='motif',
            field=models.CharField(choices=[('reforme', 'Réformé'), ('perdu', 'Perdu'), ('don', 'Don'), ('vendu', 'Vendu'), ('casse', 'Cassé'), ('vole', 'Volé'), ('retour_fournisseur', 'Retour fournisseur'), ('autre', 'Autre')], default='autre', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalarchiveitem',
            name='motif',
            field=models.CharField(choices=[('reforme', 'Réformé'), ('perdu', 'Perdu'), ('don', 'Don'), ('vendu', 'Vendu'), ('casse', 'Cassé'), ('vole', 'Volé'), ('retour_fournisseur', 'Retour fournisseur'), ('autre', 'Autre')], default='autre', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicaldetail_inventaire',
            name='etat',
            field=models.CharField(choices=[('correcte', 'correcte'), ('intru', 'intru'), ('manquant', 'manquant'), ('inconnu', 'inconnu'), ('non_affecter', 'non_affecter')], max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalinventaire_emplacement',
            name='statut',
            field=models.CharField(choices=[('Terminer', 'Terminer'), ('En attente', 'En attente'), ('En cours', 'En cours')], default='En attente', max_length=255),
        ),
    ]
