# Generated by Django 5.0.3 on 2026-04-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_archiveitem_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_inventaire',
            name='etat',
            field=models.CharField(choices=[('trouvee', 'trouvee'), ('intru', 'intru'), ('manquant', 'manquant'), ('inconnu', 'inconnu'), ('non_affecter', 'non_affecter')], max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaldetail_inventaire',
            name='etat',
            field=models.CharField(choices=[('trouvee', 'trouvee'), ('intru', 'intru'), ('manquant', 'manquant'), ('inconnu', 'inconnu'), ('non_affecter', 'non_affecter')], max_length=255),
        ),
    ]
