# Generated by Django 5.0.3 on 2026-04-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0012_detail_inventaire_allow_unknown_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldetail_inventaire',
            name='tag_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
